### ISSUE TITLE
RuntimeException: Package manager has died

### ISSUE THREAD

**Issue by chxchen** [ac-pm/Inspeckage#70]
` Process: mobi.acpm.inspeckage, PID: 9531
                                                 java.lang.RuntimeException: Package manager has died
                                                     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:111)
                                                     at mobi.acpm.inspeckage.util.PackageDetail.<init>(PackageDetail.java:43)
                                                     at mobi.acpm.inspeckage.ui.MainFragment.loadSelectedApp(MainFragment.java:307)
                                                     at mobi.acpm.inspeckage.ui.MainFragment.access$000(MainFragment.java:44)
                                                     at mobi.acpm.inspeckage.ui.MainFragment$1.onChildClick(MainFragment.java:110)`

when the app's applicationInfo is too large,it occurs.
It seems to relative with "1MB limit on a Binder transaction".

**Comment by holymonk** [comment]
got same problem
