### ISSUE TITLE
Problems in Android 7 with release 2.4 are still not fixed.

### ISSUE THREAD

**Issue by clviper** [ac-pm/Inspeckage#77]
Hi @ac-pm . This approach is not completely correct. Essentially, Inspeckage is not able to create the Inspeckage folder inside the app sandbox. As soon as you create it manually, everything starts working.

08-24 16:59:09.832 9893 9893 W System.err: java.io.IOException: Permission denied
08-24 16:59:09.833 9893 9893 W System.err: at java.io.UnixFileSystem.createFileExclusively0(Native Method)
08-24 16:59:09.833 9893 9893 W System.err: at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
08-24 16:59:09.833 9893 9893 W System.err: at java.io.File.createNewFile(File.java:948)
08-24 16:59:09.833 9893 9893 W System.err: at mobi.acpm.inspeckage.util.FileUtil.writeToFile(FileUtil.java:142)
08-24 16:59:09.834 9893 9893 W System.err: at mobi.acpm.inspeckage.util.PackageDetail.extractInfoToFile(PackageDetail.java:422)
08-24 16:59:09.834 9893 9893 W System.err: at mobi.acpm.inspeckage.ui.MainFragment.loadSelectedApp(MainFragment.java:354)
08-24 16:59:09.834 9893 9893 W System.err: at mobi.acpm.inspeckage.ui.MainFragment.access$000(MainFragment.java:44)
08-24 16:59:09.834 9893 9893 W System.err: at mobi.acpm.inspeckage.ui.MainFragment$1.onChildClick(MainFragment.java:111)
08-24 16:59:09.834 9893 9893 W System.err: at android.widget.ExpandableListView.handleItemClick(ExpandableListView.java:714)
08-24 16:59:09.834 9893 9893 W System.err: at android.widget.ExpandableListView.performItemClick(ExpandableListView.java:653)
08-24 16:59:09.834 9893 9893 W System.err: at android.widget.AbsListView$PerformClick.run(AbsListView.java:3128)
08-24 16:59:09.834 9893 9893 W System.err: at android.widget.AbsListView$3.run(AbsListView.java:4043)
08-24 16:59:09.834 9893 9893 W System.err: at android.os.Handler.handleCallback(Handler.java:751)
08-24 16:59:09.834 9893 9893 W System.err: at android.os.Handler.dispatchMessage(Handler.java:95)
08-24 16:59:09.834 9893 9893 W System.err: at android.os.Looper.loop(Looper.java:154)
08-24 16:59:09.834 9893 9893 W System.err: at android.app.ActivityThread.main(ActivityThread.java:6126)
08-24 16:59:09.834 9893 9893 W System.err: at java.lang.reflect.Method.invoke(Native Method)
08-24 16:59:09.834 9893 9893 W System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-24 16:59:09.834 9893 9893 W System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-24 16:59:09.834 9893 9893 W System.err: at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

If you need any additional help debugging this issue let me know.

Thanks.

**Comment by miaochiahao** [comment]
Hi, do you have any solutions to solve this? even manually? I've been stuck to this for a while.
